apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: money-saver-dev

resources:
- ../../base

patches:
- target:
    kind: Deployment
    name: backend
  patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/image
      value: money-saver-backend:dev
- target:
    kind: Deployment
    name: frontend
  patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/image
      value: money-saver-frontend:dev 